apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-id-getter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-id-getter
  template:
    metadata:
      labels:
        app: cluster-id-getter
    spec:
      automountServiceAccountToken: true
      serviceAccountName: license-app-sa
      containers:
        - name: app-container
          imagePullPolicy: IfNotPresent
          image: zoeimport/hellok8s:fingerprint_v1